server:
  port: 8080

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/hk-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.kk.code.*.entity
  configuration:
    #    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

